### ISSUE TITLE
Release roadmap

### ISSUE THREAD

**Issue by joemaller** [joemaller/version-everything#2]
These need to happen for 1.0

- [x] rename binary
- [x] commonjs exports
- [x] Tests
- [x] [yargs](https://www.npmjs.com/package/yargs) command line arguments
- [x] Add support for XML
- [x] Add support for YAML
- [ ] Add support for YAML frontmatter in Markdown files
- [ ] Stream support (for Gulp?)
- [x] Code coverage ([istanbul](https://istanbul.js.org/))
- [x] Travis CI

**Comment by joemaller** [comment]
YAML front matter moved to #46. 

Streams just don't seem as important as they did. dropping that idea for now
